org.gradle.jvmargs=-Xmx4000M
org.gradle.daemon=false
org.gradle.configuration-cache=true

# NeoForge: https://projects.neoforged.net/neoforged/neoforge
base_minecraft_version=26.1
minecraft_version=26.1
neoforge_version=26.1.0.3-beta
mdg_version=2.0.141

beanification_version=1.7.112
regutil_version=1.11.60
jei_version=19.8.2.99

mod_id=melongolem
mod_major_version=1.10
mod_version=0
