@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault @TypeUseAreNonnullByDefault
package tamaized.melongolem.config;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;
import tamaized.regutil.TypeUseAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;