@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.melongolem.client;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;