@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.melongolem.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;