@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.melongolem.config.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;