@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.melongolem;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;