@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.melongolem.registry;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;