@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.melongolem.registry;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;