@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.melongolem.config.common;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;