@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.melongolem.network.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;