@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.melongolem.network.client;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;