@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.melongolem.common.capability;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;