@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.melongolem.network.server;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;