@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.melongolem.network;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;