@MethodsReturnNonnullByDefault @ParametersAreNonnullByDefault
package tamaized.melongolem.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;